src/Entity/Cliente.php
<?php

namespace App\Entity;

use App\Repository\ClienteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClienteRepository::class)]
class Cliente
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $nombre;

    #[ORM\Column(type: 'string', length: 100)]
    private $apellidos;

    #[ORM\Column(type: 'string', length: 9)]
    private $telefono;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $direccion;

    #[ORM\OneToMany(mappedBy: 'cliente', targetEntity: Incidencia::class, orphanRemoval: true)]
    private $incidencias;

    public function __construct()
    {
        $this->incidencias = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellidos(): ?string
    {
        return $this->apellidos;
    }

    public function setApellidos(string $apellidos): self
    {
        $this->apellidos = $apellidos;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(?string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }
    
    public function nombreCompleto(){
        return $this->nombre . " " . $this->apellidos;
    }

    /**
     * @return Collection<int, Incidencia>
     */
    public function getIncidencias(): Collection
    {
        return $this->incidencias;
    }

    public function addIncidencia(Incidencia $incidencia): self
    {
        if (!$this->incidencias->contains($incidencia)) {
            $this->incidencias[] = $incidencia;
            $incidencia->setCliente($this);
        }

        return $this;
    }

    public function removeIncidencia(Incidencia $incidencia): self
    {
        if ($this->incidencias->removeElement($incidencia)) {
            // set the owning side to null (unless already changed)
            if ($incidencia->getCliente() === $this) {
                $incidencia->setCliente(null);
            }
        }

        return $this;
    }
}

src/Entity/Incidencia.php
<?php

namespace App\Entity;

use App\Repository\IncidenciaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: IncidenciaRepository::class)]
class Incidencia
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $titulo;

    #[ORM\Column(type: 'datetime')]
    private $fecha_creacion;

    #[ORM\Column(type: 'string', length: 20)]
    private $estado;

    #[ORM\ManyToOne(targetEntity: Cliente::class, inversedBy: 'incidencias')]
    #[ORM\JoinColumn(nullable: false)]
    private $cliente;

    #[ORM\ManyToOne(targetEntity: Usuario::class, inversedBy: 'incidencias')]
    #[ORM\JoinColumn(nullable: false)]
    private $usuario;

    public function __construct()
    {
        $this->usuario = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getFechaCreacion(): ?\DateTimeInterface
    {
        return $this->fecha_creacion;
    }

    public function setFechaCreacion(\DateTimeInterface $fecha_creacion): self
    {
        $this->fecha_creacion = $fecha_creacion;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getCliente(): ?cliente
    {
        return $this->cliente;
    }

    public function setCliente(?Cliente $cliente): self
    {
        $this->cliente = $cliente;

        return $this;
    }

    public function addUsuario(Usuario $usuario): self
    {
        if (!$this->usuario->contains($usuario)) {
            $this->usuario = $usuario;
            $usuario->setIncidencias($this);
        }

        return $this;
    }

    public function removeUsuario(Usuario $usuario): self
    {
        if ($this->usuario->removeElement($usuario)) {
            // set the owning side to null (unless already changed)
            if ($usuario->getIncidencias() === $this) {
                $usuario->setIncidencias(null);
            }
        }

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }
}

src/Controller/ClientesController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Cliente;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Validator\Constraints\NotBlank;
/**
 * Require ROLE_ADMIN for all the actions of this controller
 *
 * @IsGranted("ROLE_USER")
 */
class ClientesController extends AbstractController
{
    #[Route('/clientes', name: 'listado_clientes')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $arrayClientes = $doctrine->getRepository(Cliente::class)->findAll();
        return $this->render('clientes/index.html.twig', [
            'clientes' => $arrayClientes
        ]);
    }
    /**
     * @Route("clientes/insertar", name="insertar_cliente")
     * @param Request $request
     * @param ManagerRegistry $doctrine
     * @return type
     */
    public function insertar(Request $request,ManagerRegistry $doctrine):Response{
        //$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $cliente = new Cliente();
        $form = $this->createFormBuilder($cliente)
                ->add('nombre', TextType::class, [
                    'required' => true,
                    'constraints' => [
                        new NotBlank([
                            'message' => 'Introduzca el nombre',
                        ])
            ]
                    ])
                ->add('apellidos', TextType::class, [
                    'required' => true,
                    'constraints' => [
                        new NotBlank([
                            'message' => 'Introduzca el los apellidos',
                        ])
            ]])
                ->add('direccion', TextType::class, ['required' => false])
                ->add('telefono', TelType::class, [
                    'required' => true,
                    'constraints' => [
                        new NotBlank([
                            'message' => 'Introduzca el teléfono',
                        ])
            ]])
                ->add('enviar', SubmitType::class)
                ->getForm();
        
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $cliente = $form->getData();
            $entityManager = $doctrine->getManager();
                $entityManager->persist($cliente);
                $entityManager->flush();
                $this->addFlash("aviso", "Nuevo cliente creado");
                return $this->redirectToRoute("listado_clientes");
        }
        return $this->renderForm("clientes/insertar.html.twig", ['formulario' => $form]);
    }
    /**
     * @Route("/clientes/{id<\d+>}", name="ver_cliente")
     * @param Cliente $cliente
     * @return Response
     */
    public function ver_cliente(Cliente $cliente):Response{
         return $this->render("clientes/cliente.html.twig", ["cliente" => $cliente]);
    }
    
    /**
     * @Route("/clientes/borrar/{id<\d+>}", name="borrar_cliente")
     * @return Response
     */
    public function borrar (Cliente $cliente, ManagerRegistry $doctrine):Response{
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $entityManager = $doctrine->getManager();
        $entityManager->remove($cliente);
        $entityManager->flush();
        $this->addFlash("aviso", "Cliente borrado correctamente");
        return $this->redirectToRoute("listado_clientes");
    }
    
}

templates/clientes/cliente.html.twig
{% extends 'base.html.twig' %}

{% block title %}Clientes{% endblock %}

{% block main %}

{% for message in app.flashes('aviso') %}
    <div class="flash-notice alert alert-info">
        {{ message }}
    </div>
{% endfor %}
<h2>Consulta de clientes</h2>
<div class="cliente mb-2">
    <h3>Datos del cliente</h3>
    <div class="cliente__info ps-3">
        <p>{{ cliente.nombre }} {{ cliente.apellidos }}</p>
        <p>{{ cliente.telefono }}</p>
        <p> 
            {% if cliente.direccion is not empty %} 
               {{ cliente.direccion  }} 
            {%else%} 
                Sin datos de direccion
            {% endif %} 
        </p>
    </div>
        <h3>Datos de la incidencia</h3>
    <div class="cliente__incidencias ">
        {% if cliente.incidencias is not empty %}
            {% for incidencia in cliente.incidencias %}
                <div class="incidencia ps-3 border-bottom border-dark p-2">
                <p>{{ incidencia.titulo }} <a href="{{ path("borrar_incidencia", {id: incidencia.id, cliente:cliente.id}) }}"><i class="fa-solid fa-circle-minus"></i></a> <a href="{{ path("editar_incidencia", {id: incidencia.id, cliente:cliente.id}) }}"><i class="fas fa-edit"></i></a></p>
                <p> Iniciada el: {{ incidencia.fechaCreacion | date("Y-m-d") }}</p>
                <p>{{ incidencia.estado }}</p>
            </div>
            {% endfor %}
        {% else %}
            <p class="ps-3 p-2">Todavía no ha registrado incidencias </p>
        {% endif %}
        <a href="{{ path("insertar_incidenciaCliente", {cliente:cliente.id}) }}" class="btn boton mt-2 mb-2 text-white">Nueva incidencia</a>
    </div>
</div>
<a href="{{ path("listado_clientes") }}" class="btn btn-light">Atrás</a>
{% endblock %}{# empty Twig template #}

templates/clientes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Clientes{% endblock %}

{% block main %}

{% for message in app.flashes('aviso') %}
    <div class="flash-notice alert alert-info">
        {{ message }}
    </div>
{% endfor %}
<h2>Listado de clientes</h2>
{% if clientes is not empty %}
<div class="clientes">
    {% for cliente in clientes %}
        <div class="cliente">
            <a href="{{ path('ver_cliente', {id:cliente.id}) }}">{{ cliente.nombre }} {{ cliente.apellidos }}</a> <a href="{{ path("borrar_cliente", {id:cliente.id}) }}"><i class="fa-solid fa-circle-minus"></i></a>
        </div>
    
{% endfor %}
{% else %}
    <p>Todavía no hay ningún cliente</p>
{% endif %}
</div>
<a href="{{ path('insertar_cliente')}}" class="btn boton text-white">Añadir cliente</a>
{% endblock %}

templates/clientes/insertar.html.twig
{# empty Twig template #}
{% extends 'base.html.twig' %}

{% block title %}Alta de clientes{% endblock %}

{% block main %}
<h2>Nuevo cliente</h2>
{% for message in app.flashes('aviso') %}
    <div class="flash-notice">
        {{ message }}
    </div>
{% endfor %}

{{ form_start(formulario, {'attr': {'class': 'w-50 m-auto'}} ) }}
{{ form_row(formulario.nombre, {'attr': {'class': 'form-control mb-2'}} ) }}
{{ form_row(formulario.apellidos, {'attr': {'class': 'form-control mb-2'}} ) }}
{{ form_row(formulario.direccion, {'attr': {'class': 'form-control mb-2'}} ) }}
{{ form_row(formulario.telefono, {'attr': {'class': 'form-control mb-2'}} ) }}
{{ form_row(formulario.enviar, {
            label: 'Registrar cliente', 'attr': {'class': 'btn boton mb-2 w-100'}
        }) }}
{{ form_end(formulario) }}
<a href="{{ path("listado_clientes") }}" class="btn btn-light">Atrás</a>
{% endblock %}